// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Obsthandel.Backend.Select_Order(System.String)~System.ComponentModel.BindingList{Obsthandel.Order}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Obsthandel.Backend.Get_Kunde(System.Int32)~Obsthandel.Kunde")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Obsthandel.Backend.Insert_Kunde(System.String,System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Obsthandel.Backend.Update_Kunde(System.String,System.String,System.String,System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Obsthandel.Backend.Select_Kunde(System.String)~System.ComponentModel.BindingList{Obsthandel.Kunde}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Obsthandel.Backend.Select_Kunde(System.String,System.String)~System.ComponentModel.BindingList{Obsthandel.Kunde}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Obsthandel.Backend.Select_Artikel(System.String)~System.ComponentModel.BindingList{Obsthandel.Artikel}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Obsthandel.Backend.Select_Ort(System.String)~System.Collections.Generic.List{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Obsthandel.Backend.Select_Artikel(System.String,System.String)~System.ComponentModel.BindingList{Obsthandel.Artikel}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Codequalität", "IDE0052:Ungelesene private Member entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:Obsthandel.Backend.frontend")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Stil", "IDE0044:Modifizierer \"readonly\" hinzufügen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:Obsthandel.Backend.frontend")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Obsthandel.Backend.Update_Artikel(System.String,System.Double,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Obsthandel.Backend.Get_Kunde(System.Int32)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Obsthandel.Backend.Insert_Query(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Obsthandel.Backend.Select_Position(System.String,System.Int32)~System.ComponentModel.BindingList{Obsthandel.Position}")]
